In [3]:
# Snippet to import utils module
import os, sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

from utils import utils
import pandas as pd

In [4]:
dir = "../data/CulinaryDB/"
recipes = pd.read_csv(dir+"01_Recipe_Details.csv", index_col="Recipe ID")
recipes

,Title,Source,Cuisine
Recipe ID,,,
1,5 spice vegetable fried rice,TARLA_DALAL,Indian Subcontinent
2,aachar aaloo,TARLA_DALAL,Indian Subcontinent
3,aadu lassan keri nu athanu,TARLA_DALAL,Indian Subcontinent
4,aaloo kofta,TARLA_DALAL,Indian Subcontinent
5,aaloo tamatar subzi,TARLA_DALAL,Indian Subcontinent
...,...,...,...
45768,Strawberries & Cream Frappé,EPICURIOUS,USA
45769,Chocolate Whiskey Bundt Cake,EPICURIOUS,USA
45770,"Wild Rice with Butternut Squash, Leeks, and Corn",EPICURIOUS,USA
45771,Fruit Crumble,EPICURIOUS,USA
45772,Enlightened Chicken Pot Pie,EPICURIOUS,USA

In [5]:
ingredients = pd.read_csv(dir+"02_Ingredients.csv", index_col="Entity ID")
ingredients

          Aliased Ingredient Name    Ingredient Synonyms  Category
Entity ID
0                             Egg                    egg      Meat
2                           Bread             bread; bun    Bakery
3                       Rye Bread              bread-rye    Bakery
4                   Wheaten Bread          bread-wheaten    Bakery
5                     White Bread  bread-white; baguette    Bakery
...                           ...                    ...       ...
998                   Citric Acid            citric acid  Additive
999                 Cooking Spray          cooking spray  Additive
1000                      Gelatin                gelatin  Additive
1001                Food Coloring          food coloring  Additive
1002                 Liquid Smoke           liquid smoke  Additive

[930 rows x 3 columns]

In [6]:
compounds = pd.read_csv(dir+"03_Compound_Ingredients.csv", index_col="entity_id")
compounds

,Compound Ingredient Name,Compound Ingredient Synonyms,Contituent Ingredients,Category
entity_id,,,,
2000,Garam Masala,garam masala,"black pepper, mace, cinnamon, clove, cardamom,...",Spice
2001,Ginger Garlic Paste,ginger garlic paste,"ginger, garlic",Spice
2002,Coriander Cumin Seed Powder,coriander cumin seed powder,"coriander, cumin",Spice
2003,Chaat Masala,chaat masala,"asafoetida, mango, black salt, cayenne, garlic...",Spice
2004,Sambar Powder,sambar powder,"pigeon pea, coriander, chickpea, cumin, black ...",Spice
...,...,...,...,...
2098,Rabbit,rabbit,"rabbit, rabbit-european, meat",Meat
2099,Haddock,haddock,"haddock, haddock-norway",Fish
2100,Persimmon,persimmon,"persimmon,persimmon-common",Fruit
2101,Apple Sauce,apple=sauce,"apple sauce, apple, lemon juice, sugar",Dish
2102,Cider Vinegar,soy cream; soya cream,"soy cream, soy milk, cooking oil, agave, cider...",Dish

In [7]:
aliases = pd.read_csv(dir+"04_Recipe-Ingredients_Aliases.csv")
aliases

,Recipe ID,Original Ingredient Name,Aliased Ingredient Name,Entity ID
0,1,capsicum,capsicum,362
1,1,green bell pepper,pepper bell,362
2,1,soy sauce,soy sauce,291
3,1,sunflower oil,sunflower,426
4,2,buttermilk,buttermilk,61
...,...,...,...,...
456274,45772,1/2 tsp salt,salt,778
456275,45772,"1 yellow squash, diced",squash yellow,493
456276,45772,1/2 tsp dried thyme,thyme,269
456277,45772,1 tsp Worcestershire sauce,worcestershire sauce,2031
456278,45772,"1 small zucchini, diced",zucchini,969